import ExcelJS from 'exceljs'
import PDFDocument from 'pdfkit'

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end()

  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: 'Method not allowed' })
  }

  try {
    const { type, data, format, department, generatedBy, generatedAt, metadata } = req.body

    if (!type || !data || !format) {
      return res.status(400).json({ success: false, error: 'Missing required fields' })
    }

    const filename = `${type}_${department}_${new Date().toISOString().split('T')[0]}`

    switch (format.toLowerCase()) {
      case 'pdf':
        await generatePDF(res, { type, data, metadata, filename, generatedBy, generatedAt })
        break
      case 'excel':
        await generateExcel(res, { type, data, metadata, filename, generatedBy, generatedAt })
        break
      case 'csv':
        await generateCSV(res, { type, data, metadata, filename, generatedBy, generatedAt })
        break
      default:
        return res.status(400).json({ success: false, error: 'Unsupported format' })
    }
  } catch (error) {
    console.error('Export error:', error)
    return res.status(500).json({ success: false, error: 'Export failed' })
  }
}

async function generatePDF(res, { type, data, metadata, filename, generatedBy, generatedAt }) {
  const doc = new PDFDocument({ margin: 50 })
  
  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.pdf"`)
  
  doc.pipe(res)

  // Header
  doc.fontSize(20).text(metadata.reportTitle, { align: 'center' })
  doc.fontSize(12).text(`Department: ${metadata.departmentName}`, { align: 'center' })
  doc.fontSize(10).text(`Generated by: ${generatedBy} on ${new Date(generatedAt).toLocaleString()}`, { align: 'center' })
  doc.moveDown(2)

  switch (type) {
    case 'department-summary':
      generateDepartmentSummaryPDF(doc, data)
      break
    case 'classwise-performance':
      generateClasswisePerformancePDF(doc, data)
      break
    case 'failed-dispatches':
      generateFailedDispatchesPDF(doc, data)
      break
    case 'subject-analysis':
      generateSubjectAnalysisPDF(doc, data)
      break
  }

  doc.end()
}

function generateDepartmentSummaryPDF(doc, data) {
  doc.fontSize(14).text('Department Summary Report', { underline: true })
  doc.moveDown()

  doc.fontSize(12)
  doc.text(`Total Students: ${data.totalStudents}`)
  doc.text(`Total Marksheets: ${data.totalMarksheets}`)
  doc.text(`Dispatched: ${data.dispatched}`)
  doc.text(`Pending: ${data.pending}`)
  doc.text(`Failed: ${data.failed}`)
  doc.moveDown()

  if (data.yearWiseBreakdown && data.yearWiseBreakdown.length > 0) {
    doc.fontSize(14).text('Year-wise Breakdown:', { underline: true })
    doc.moveDown(0.5)
    
    data.yearWiseBreakdown.forEach(year => {
      doc.fontSize(12).text(`Year ${year._id}:`)
      doc.text(`  Students: ${year.count}`)
      doc.text(`  Marksheets: ${year.marksheets}`)
      doc.moveDown(0.3)
    })
  }
}

function generateClasswisePerformancePDF(doc, data) {
  doc.fontSize(14).text('Classwise Performance Report', { underline: true })
  doc.moveDown()

  data.forEach(classData => {
    doc.fontSize(12).text(`${classData.branch} - Year ${classData.year}`, { underline: true })
    doc.text(`Total Students: ${classData.totalStudents}`)
    doc.text(`Dispatched: ${classData.dispatched}`)
    doc.text(`Pending: ${classData.pending}`)
    doc.text(`Dispatch Rate: ${classData.dispatchRate}%`)
    doc.moveDown()
  })
}

function generateFailedDispatchesPDF(doc, data) {
  doc.fontSize(14).text('Failed Dispatches Report', { underline: true })
  doc.moveDown()

  if (data.length === 0) {
    doc.text('No failed dispatches found.')
    return
  }

  data.forEach((marksheet, index) => {
    doc.fontSize(10)
    doc.text(`${index + 1}. ${marksheet.studentName} (${marksheet.registerNumber})`)
    doc.text(`   Branch: ${marksheet.branch}, Year: ${marksheet.year}`)
    doc.text(`   Attempts: ${marksheet.dispatchAttempts}`)
    doc.text(`   Last Attempt: ${new Date(marksheet.lastDispatchAttempt).toLocaleDateString()}`)
    doc.moveDown(0.3)
  })
}

function generateSubjectAnalysisPDF(doc, data) {
  doc.fontSize(14).text('Subject Analysis Report', { underline: true })
  doc.moveDown()

  data.forEach(subject => {
    doc.fontSize(12).text(`${subject.subjectName} (${subject.subjectCode})`, { underline: true })
    doc.text(`Total Enrollments: ${subject.totalEnrollments}`)
    doc.text(`Pass Rate: ${subject.passRate}%`)
    doc.text(`Average Grade: ${subject.averageGrade}`)
    doc.moveDown()
  })
}

async function generateExcel(res, { type, data, metadata, filename, generatedBy, generatedAt }) {
  const workbook = new ExcelJS.Workbook()
  const worksheet = workbook.addWorksheet('Report')

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.xlsx"`)

  // Header styling
  const headerStyle = {
    font: { bold: true, size: 14 },
    alignment: { horizontal: 'center' },
    fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE6E6FA' } }
  }

  // Add title
  worksheet.addRow([metadata.reportTitle])
  worksheet.getRow(1).font = { bold: true, size: 16 }
  worksheet.getRow(1).alignment = { horizontal: 'center' }

  worksheet.addRow([`Department: ${metadata.departmentName}`])
  worksheet.addRow([`Generated by: ${generatedBy} on ${new Date(generatedAt).toLocaleString()}`])
  worksheet.addRow([]) // Empty row

  switch (type) {
    case 'department-summary':
      generateDepartmentSummaryExcel(worksheet, data, headerStyle)
      break
    case 'classwise-performance':
      generateClasswisePerformanceExcel(worksheet, data, headerStyle)
      break
    case 'failed-dispatches':
      generateFailedDispatchesExcel(worksheet, data, headerStyle)
      break
    case 'subject-analysis':
      generateSubjectAnalysisExcel(worksheet, data, headerStyle)
      break
  }

  // Auto-fit columns
  worksheet.columns.forEach(column => {
    column.width = Math.max(10, column.width || 0)
  })

  await workbook.xlsx.write(res)
  res.end()
}

function generateDepartmentSummaryExcel(worksheet, data, headerStyle) {
  worksheet.addRow(['Summary Statistics'])
  worksheet.getRow(worksheet.rowCount).style = headerStyle

  worksheet.addRow(['Metric', 'Count'])
  worksheet.addRow(['Total Students', data.totalStudents])
  worksheet.addRow(['Total Marksheets', data.totalMarksheets])
  worksheet.addRow(['Dispatched', data.dispatched])
  worksheet.addRow(['Pending', data.pending])
  worksheet.addRow(['Failed', data.failed])

  if (data.yearWiseBreakdown && data.yearWiseBreakdown.length > 0) {
    worksheet.addRow([])
    worksheet.addRow(['Year-wise Breakdown'])
    worksheet.getRow(worksheet.rowCount).style = headerStyle
    
    worksheet.addRow(['Year', 'Students', 'Marksheets'])
    data.yearWiseBreakdown.forEach(year => {
      worksheet.addRow([year._id, year.count, year.marksheets])
    })
  }
}

function generateClasswisePerformanceExcel(worksheet, data, headerStyle) {
  worksheet.addRow(['Branch', 'Year', 'Total Students', 'Dispatched', 'Pending', 'Dispatch Rate (%)'])
  worksheet.getRow(worksheet.rowCount).style = headerStyle

  data.forEach(classData => {
    worksheet.addRow([
      classData.branch,
      classData.year,
      classData.totalStudents,
      classData.dispatched,
      classData.pending,
      classData.dispatchRate
    ])
  })
}

function generateFailedDispatchesExcel(worksheet, data, headerStyle) {
  if (data.length === 0) {
    worksheet.addRow(['No failed dispatches found'])
    return
  }

  worksheet.addRow(['Student Name', 'Register Number', 'Branch', 'Year', 'Attempts', 'Last Attempt'])
  worksheet.getRow(worksheet.rowCount).style = headerStyle

  data.forEach(marksheet => {
    worksheet.addRow([
      marksheet.studentName,
      marksheet.registerNumber,
      marksheet.branch,
      marksheet.year,
      marksheet.dispatchAttempts,
      new Date(marksheet.lastDispatchAttempt).toLocaleDateString()
    ])
  })
}

function generateSubjectAnalysisExcel(worksheet, data, headerStyle) {
  worksheet.addRow(['Subject Name', 'Subject Code', 'Total Enrollments', 'Pass Rate (%)', 'Average Grade'])
  worksheet.getRow(worksheet.rowCount).style = headerStyle

  data.forEach(subject => {
    worksheet.addRow([
      subject.subjectName,
      subject.subjectCode,
      subject.totalEnrollments,
      subject.passRate,
      subject.averageGrade
    ])
  })
}

async function generateCSV(res, { type, data, metadata, filename, generatedBy, generatedAt }) {
  res.setHeader('Content-Type', 'text/csv')
  res.setHeader('Content-Disposition', `attachment; filename="${filename}.csv"`)

  let csvContent = `${metadata.reportTitle}\n`
  csvContent += `Department: ${metadata.departmentName}\n`
  csvContent += `Generated by: ${generatedBy} on ${new Date(generatedAt).toLocaleString()}\n\n`

  switch (type) {
    case 'department-summary':
      csvContent += generateDepartmentSummaryCSV(data)
      break
    case 'classwise-performance':
      csvContent += generateClasswisePerformanceCSV(data)
      break
    case 'failed-dispatches':
      csvContent += generateFailedDispatchesCSV(data)
      break
    case 'subject-analysis':
      csvContent += generateSubjectAnalysisCSV(data)
      break
  }

  res.send(csvContent)
}

function generateDepartmentSummaryCSV(data) {
  let csv = 'Summary Statistics\n'
  csv += 'Metric,Count\n'
  csv += `Total Students,${data.totalStudents}\n`
  csv += `Total Marksheets,${data.totalMarksheets}\n`
  csv += `Dispatched,${data.dispatched}\n`
  csv += `Pending,${data.pending}\n`
  csv += `Failed,${data.failed}\n\n`

  if (data.yearWiseBreakdown && data.yearWiseBreakdown.length > 0) {
    csv += 'Year-wise Breakdown\n'
    csv += 'Year,Students,Marksheets\n'
    data.yearWiseBreakdown.forEach(year => {
      csv += `${year._id},${year.count},${year.marksheets}\n`
    })
  }

  return csv
}

function generateClasswisePerformanceCSV(data) {
  let csv = 'Branch,Year,Total Students,Dispatched,Pending,Dispatch Rate (%)\n'
  
  data.forEach(classData => {
    csv += `"${classData.branch}",${classData.year},${classData.totalStudents},${classData.dispatched},${classData.pending},${classData.dispatchRate}\n`
  })

  return csv
}

function generateFailedDispatchesCSV(data) {
  if (data.length === 0) {
    return 'No failed dispatches found\n'
  }

  let csv = 'Student Name,Register Number,Branch,Year,Attempts,Last Attempt\n'
  
  data.forEach(marksheet => {
    csv += `"${marksheet.studentName}","${marksheet.registerNumber}","${marksheet.branch}",${marksheet.year},${marksheet.dispatchAttempts},"${new Date(marksheet.lastDispatchAttempt).toLocaleDateString()}"\n`
  })

  return csv
}

function generateSubjectAnalysisCSV(data) {
  let csv = 'Subject Name,Subject Code,Total Enrollments,Pass Rate (%),Average Grade\n'
  
  data.forEach(subject => {
    csv += `"${subject.subjectName}","${subject.subjectCode}",${subject.totalEnrollments},${subject.passRate},"${subject.averageGrade}"\n`
  })

  return csv
}